sudo: enabled
language: cpp
compiler:
  - gcc
cache:
  - ccache
env:
  - global:
    - MAKEFLAGS="-j 2"

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libboost-all-dev libcv-dev libopencv-dev libopencv-contrib-dev libopencv-gpu-dev libqt4-dev libqwt5-qt4-dev libqglviewer-dev cmake build-essential libfftw3-dev ccache

before_script:
  - cp cedar.conf.example cedar.conf
  - mkdir build
  - cd build

script:
  - cmake ..
  - make -j 2
  - make test
  - sudo make install
